import Layout from "./layout/layout";
import Login from "./pages/login";
import Signup from "./pages/signup";
import Header from "./component/header";
import Footer from "./component/footer";
import Home from "./pages/home";
import Slider from './component/slider'
import Categories from './component/categories'
import Featured from './component/Featured'
import Testimonial from './component/testimonial'
import Card from './component/Card'
import Loader from './component/Loader'
import SortNav from './component/SortNav'
import Review from './component/Review'
import Cart from './pages/Cart'
import ProductDetail from './pages/ProductDetail'
import Electronics from './pages/Electronics'
import Grocery from './pages/Grocery'
import Clothing from './pages/Clothing'
import CartBtn from './component/CartBtn'
import store from './redux/store'
import Input from './component/Input'
import Button from './component/Button'
import Form from './component/Form'
import logo from './assets/cart.png'
import Profile from "./pages/Profile";
import Ordersummary from "./pages/Ordersummary";
export { Ordersummary, Profile, Form, Input, Button, logo, Login, Signup, store, Electronics, Grocery, Clothing, ProductDetail, Cart, Review, Loader, SortNav, Card, Slider, Categories, Featured, Testimonial, Layout, Header, Footer, Home, CartBtn };